name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main
  # TODO(sileht): delete me, here just for CI setup
  push:
    branches:
      - main

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linters:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.7

      - name: Setup Python 🔧
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12.4

      - name: Download actionlint
        id: get_actionlint
        # yamllint disable-line rule:line-length
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.7.1

      - name: Test 🔍
        run: |
          # nosemgrep: generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip
          pip install semgrep yamllint
          semgrep --config=auto --error
          yamllint .
          ${{ steps.get_actionlint.outputs.executable }} -color

  local-action:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.7
      - name:
        run: docker compose up -d
      - name: Run action 🔍
        uses: ./
        with:
          token: fake-valid-token
          report_paths: zfixtures/junit_example.xml
          mergify_api_server: http://localhost:1080
